// commands/menuAvancado.js
function handle() {
  return [
    '🤖 *Menu Avançado do Marvinho*',
    'Aqui está o guia completo de comandos com exemplos e dicas:',
    '',
    '─────────────',
    '🛒 *Lista de Compras* - Ideal para fazer uma lista de compras do mercado e ir riscando os itens conforme põe eles no carrinho!',
    '',
    '  • `comprar arroz`',
    '      – Adiciona “arroz” na lista de compras (você pode enviar várias linhas assim:',
    ' *comprar arroz*',
    ' *feijão*',
    ' *frango*',
    ' *macarrão*',
    '',
    '  • `lista de compras`',
    '      – Exibe todos os itens da lista numerados na ordem que foram adicionados',
    '',
    '  • `comprei 2`',
    '      – Risca o item de ID 2 (marca como comprado)',
    '',
    '  • `comprei arroz`',
    '      – Também funciona por texto exato para riscar o item da lista',
    '',
    '  • `limpar lista`',
    '      – Remove todos os itens da sua lista de compras!',
    '',
    '🎁 *Wishlist* - Ótimo para registrar itens que você deseja comprar um dia, lugares que deseja visitar,  qualquer tipo de sonho que você quiser!',
    '',
    '  • `wishlist celular de última geração`',
    '      – Adiciona “celular de última geração” à sua lista de desejos',
    '',
    '  • `wishlist`',
    '      – Exibe desejos atuais numerados',
    '',
    '  • `unwish 1`',
    '      – Remove o item de ID 1 da lista',
    '',
    '  • `unwish fone novo`',
    '      – Remove por texto também',
    '',
    '💸 *Gastos* - Interessante pra registrar rapido os gastos de uam viagem e pagar o amiguinho depois',
    '',
    '  • `gasto Joaquim mercado 45,00`',
    '      – Registra R$ 45,00 com “mercado” pago pelo Joaquim',
    '',
    '  • `gastos`',
    '      – Exibe todos os gastos numerados',
    '',
    '  • `remover gasto 3`',
    '      – Remove o gasto de ID 3',
    '',
    '  • `remover gasto uber 15`',
    '      – Remove por texto',
    '',
    '  • `limpar gastos`',
    '      – Zera todos os gastos (mantém cabeçalho)',
    '',
    '📝 *To-Do* - Para registrar aquela tarefa que voce quer fazer no seu dia',
    '',
    '  • `todo Ler o guia do mochileiro das galaxias`',
    '      – Adiciona “Ler o guia do mochileiro das galaxias" à lista de tarefas',
    '',
    '  • `to-do`',
    '      – Exibe tarefas atuais numeradas',
    '',
    '  • `done 2`',
    '      – Risca a tarefa #2 na lista, marcando como concluída',
    '',
    '  • `done Reunião`',
    '      – Também suporta texto exato para riscar a tarefa da lista',
    '',
    '  • `limpar to-do`',
    '      – Zera a sua lista de tarefas!',
    '',
    '─────────────',
    'Para voltar ao menu simples, digite *menu* ou siga com o comando que desejar (:'
  ].join('\n');
}

module.exports = { handle };
