// commands/menuAvancado.js
function handle() {
  return [
    '🤖 *Menu Avançado do Marvinho*',
    'Aqui está o guia completo de comandos com exemplos e dicas:',
    '',
    '──────────────────────────',
    '🛒 *Lista de Compras*',
    '  • `comprar arroz`',
    '      – Adiciona “arroz” (você pode enviar várias linhas: `comprar arroz\\nfeijão`)',
    '  • `lista de compras`',
    '      – Exibe todos os itens, numerados como `ID. item`',
    '  • `comprei 2`',
    '      – Risc(@) o item de ID 2 (marca como comprado)',
    '  • `comprei arroz`',
    '      – Também funciona por texto exato',
    '  • `limpar lista`',
    '      – Remove todos os itens, preservando o cabeçalho',
    '',
    '🎁 *Wishlist*',
    '  • `wishlist celular`',
    '      – Adiciona “celular” à sua lista de desejos',
    '  • `wishlist`',
    '      – Exibe desejos atuais numerados',
    '  • `unwish 1`',
    '      – Risc(@) o ID 1',
    '  • `unwish fone`',
    '      – Risc(@) por texto também',
    '',
    '💸 *Gastos*',
    '  • `gasto mercado 45,00`',
    '      – Registra R$ 45,00 com “mercado”',
    '  • `gastos`',
    '      – Exibe todos os gastos numerados',
    '  • `remover gasto 3`',
    '      – Remove/risc ID 3',
    '  • `remover gasto uber 15`',
    '      – Remove/risc por texto',
    '  • `limpar gastos`',
    '      – Zera todos os gastos (mantém cabeçalho)',
    '',
    '📝 *To-Do*',
    '  • `todo Estudar VSCode`',
    '      – Adiciona “Estudar VSCode” à lista de tarefas',
    '  • `to-do`',
    '      – Exibe tarefas atuais numeradas',
    '  • `done 2`',
    '      – Risc(@) o ID 2 como concluído',
    '  • `done Reunião`',
    '      – Também suporta texto exato',
    '  • `limpar to-do`',
    '      – Zera todas as tarefas (mantém cabeçalho)',
    '',
    '──────────────────────────',
    'Para voltar ao menu simples, digite *menu*'
  ].join('\n');
}

module.exports = { handle };
